### ISSUE TITLE
Problema de actualización de rama

### ISSUE THREAD

**Issue by AGuerrav** [RoxanaCS/cardify#4]
mi git local no identifica la rama RA-proyectoHover, podrias actualizar el master a ver si apuntando ahi puedo bajar los cambios?

**Comment by RoxanaCS** [comment]
Cuando cambio de rama en git bash se actualizan los archivos en mi pc correspondiente al estado de cada rama, entonces en la master no tengo los últimos cambios que están en RA-proyectoHover.

**Comment by AGuerrav** [comment]
Actualicé el fork, realizando un pull request inverso y luego descargue los cambios a mi local, y ya tengo todo actualizado, cierro Issue solucionado.
