### ISSUE TITLE
último Pull request 

### ISSUE THREAD

**Issue by RoxanaCS** [RoxanaCS/cardify#8]
Actualicé al último pull request y no me corre la última funcionalidad implementada (lo del browserify). Será que debo instalar algo más?

**Comment by AGuerrav** [comment]
deje la linea comentada en el html, del archivo enlazado al browserify, para poder seguir haciendo cambios en el app.js y verlos en el demo, ya que broserify no se actualiza solo.

**Comment by RoxanaCS** [comment]
ahh ahora entiendo! Gracias, ya probé instalando broserify y todo ok!

**Comment by AGuerrav** [comment]
no esta todo ok, subo un cambio ahora en browserify y ahora si anda todo ok :)
